Packer base
Otus-DevOps-2022-05/i820_infra pull request #4
Opened 2022-07-26 21:53 UTC by i820

# Выполнено ДЗ №7 Сборка образов VM при помощи Packer

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Создан шаблон для Packer, переменные вынесены в variables.json

## Как запустить проект:
 - Заполнить файл variables.json.examples (y_memory - количество памяти в ГБ, y_cores - количество ядер, y_zone - зона
 - Выполнить команду packer build -var-file variables.json.example ubuntu16.json

## Как проверить работоспособность:
 - Должен создастся образ reddit-base

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2022-07-27 15:23 UTC, mrgreyves requested changes
Здравствуйте!)
Вам нужно добавить фейковый ключик для того чтобы прошла проверка =)
Выглядит как приключение на 15 минут =)

2022-07-27 17:55 UTC, i820 commented
Добрый вечер!
Добавил ключ, тест прошел.
Теперь для проверки нужно будет подменить файл key.json

2022-07-28 11:29 UTC, mrgreyves approved these changes
Здравствуйте!)
Надеюсь вы не закоммитили валидный ключик к вашему облаку?)
Если такое произошло, просто сгенерируйте новый =)

2022-07-28 11:31 UTC, i820 commented
Здравствуйте, нет файлик пустой

2022-07-28 11:33 UTC, merged